export const SupabaseTheme = {
    'theme-light': {
        colors: {
            brand: 'var(--color-theme-light-primary)',
            brandAccent: 'var(--color-theme-light-primary)',
            brandButtonText: 'var(--color-theme-light-text)',
            defaultButtonBackground: 'var(--color-theme-light-secondary)',
            defaultButtonBackgroundHover: 'var(--color-theme-light-secondary-darkness)',
            defaultButtonBorder: 'transparent',
            defaultButtonText: 'var(--color-theme-light-text-secondary)',
            dividerBackground: 'transparent',
            inputBackground: 'var(--color-theme-light-bg)',
            inputBorder: 'var(--color-theme-light-primary)',
            inputBorderHover: 'var(--color-theme-light-primary-darkness)',
            inputBorderFocus: 'var(--color-theme-light-primary-darkness)',
            inputText: 'var(--color-theme-light-text)',
            inputLabelText: 'var(--color-theme-light-text-secondary)',
            inputPlaceholder: 'var(--color-theme-light-text)',
            messageText: 'var(--color-theme-light-text)',
            messageTextDanger: 'var(--color-theme-light-warning)',
            anchorTextColor: 'var(--color-theme-light-text-secondary)',
            anchorTextHoverColor: 'var(--color-theme-light-text-secondary)',
        },
        space: {
          spaceSmall: '2px',
          spaceMedium: '4px',
          spaceLarge: '8px',
          labelBottomMargin: '4px',
          anchorBottomMargin: '2px',
          emailInputSpacing: '2px',
          socialAuthSpacing: '4px',
          buttonPadding: '5px 8px',
          inputPadding: '5px 8px',
        },
        borderWidths: {
          buttonBorderWidth: '1px',
          inputBorderWidth: '1px',
        },
        radii: {
          borderRadiusButton: '4px',
          buttonBorderRadius: '4px',
          inputBorderRadius: '4px',
        },
    },
    'theme-dark': {
        colors: {
            brand: 'var(--color-theme-dark-primary)',
            brandAccent: 'var(--color-theme-dark-primary)',
            brandButtonText: 'var(--color-theme-dark-text)',
            defaultButtonBackground: 'var(--color-theme-dark-secondary)',
            defaultButtonBackgroundHover: 'var(--color-theme-dark-secondary-darkness)',
            defaultButtonBorder: 'transparent',
            defaultButtonText: 'var(--color-theme-dark-text-secondary)',
            dividerBackground: 'transparent',
            inputBackground: 'var(--color-theme-dark-bg)',
            inputBorder: 'var(--color-theme-dark-primary)',
            inputBorderHover: 'var(--color-theme-dark-primary-darkness)',
            inputBorderFocus: 'var(--color-theme-dark-primary-darkness)',
            inputText: 'var(--color-theme-dark-text)',
            inputLabelText: 'var(--color-theme-dark-text-secondary)',
            inputPlaceholder: 'var(--color-theme-dark-text)',
            messageText: 'var(--color-theme-dark-text)',
            messageTextDanger: 'var(--color-theme-dark-warning)',
            anchorTextColor: 'var(--color-theme-dark-text-secondary)',
            anchorTextHoverColor: 'var(--color-theme-dark-text-secondary)',
        },
        space: {
          spaceSmall: '2px',
          spaceMedium: '4px',
          spaceLarge: '8px',
          labelBottomMargin: '4px',
          anchorBottomMargin: '2px',
          emailInputSpacing: '2px',
          socialAuthSpacing: '4px',
          buttonPadding: '5px 8px',
          inputPadding: '5px 8px',
        },
        borderWidths: {
          buttonBorderWidth: '1px',
          inputBorderWidth: '1px',
        },
        radii: {
          borderRadiusButton: '4px',
          buttonBorderRadius: '4px',
          inputBorderRadius: '4px',
        },
    },
}
